version: '1'
services:
  flight-app-js:
    build:
      context: ./flight-app-js
    ports:
      - "3000:3000"

  flight-app-py:
    build:
      context: ./flight-app-py
    ports:
      - "5000:5000"

  alloy:
    volumes:
      - './alloy/config.alloy:/etc/alloy/config.alloy'
    ports:
      - '12345:12345'
    image: 'grafana/alloy:latest'
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'